"use server";

import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export async function createShipment(formData: FormData) {
  const supabase = await createClient();

  const sender = formData.get("sender") as string;
  const receiver = formData.get("receiver") as string;
  const origin = formData.get("origin") as string;
  const destination = formData.get("destination") as string;
  const service = formData.get("service") as string;
  const vehicle = formData.get("vehicle") as string;
  const receiver_phone = (formData.get("receiver_phone") as string) || null;

  // Insert shipment (resi auto-generated by database)
  const { data: shipment, error: shipmentError } = await supabase
    .from("shipments")
    .insert({ sender, receiver, origin, destination, service, vehicle, receiver_phone })
    .select()
    .single();

  if (shipmentError || !shipment) {
    return { error: "Gagal membuat order. Silakan coba lagi." };
  }

  // Insert first tracking event
  const { error: eventError } = await supabase
    .from("tracking_events")
    .insert({
      shipment_id: shipment.id,
      location: origin,
      status: "Barang diterima di gudang",
      completed: true,
    });

  if (eventError) {
    return { error: "Order dibuat tapi gagal menambah status awal." };
  }

  redirect(`/admin/orders/${shipment.id}`);
}
