"use server";

import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export async function createShipment(formData: FormData) {
  const supabase = await createClient();

  const sender = formData.get("sender") as string;
  const receiver = formData.get("receiver") as string;
  const origin = formData.get("origin") as string;
  const destination = formData.get("destination") as string;
  const service = formData.get("service") as string;
  const vehicle = formData.get("vehicle") as string;
  const receiver_phone = (formData.get("receiver_phone") as string) || null;

  // Build insert data — receiver_phone opsional
  const insertData: Record<string, string | null> = {
    sender,
    receiver,
    origin,
    destination,
    service,
    vehicle,
  };
  if (receiver_phone) {
    insertData.receiver_phone = receiver_phone;
  }

  // Insert shipment (resi auto-generated by database)
  const { data: shipment, error: shipmentError } = await supabase
    .from("shipments")
    .insert(insertData)
    .select()
    .single();

  if (shipmentError || !shipment) {
    // Kalau error karena receiver_phone belum ada, coba tanpa field itu
    if (shipmentError?.message?.includes("receiver_phone")) {
      const { data: retry, error: retryError } = await supabase
        .from("shipments")
        .insert({ sender, receiver, origin, destination, service, vehicle })
        .select()
        .single();

      if (retryError || !retry) {
        return { error: `Gagal membuat order: ${retryError?.message}` };
      }

      // Insert first tracking event
      await supabase.from("tracking_events").insert({
        shipment_id: retry.id,
        location: origin,
        status: "Barang diterima di gudang",
        completed: true,
      });

      redirect(`/admin/orders/${retry.id}`);
    }

    return { error: `Gagal membuat order: ${shipmentError?.message}` };
  }

  // Insert first tracking event
  const { error: eventError } = await supabase
    .from("tracking_events")
    .insert({
      shipment_id: shipment.id,
      location: origin,
      status: "Barang diterima di gudang",
      completed: true,
    });

  if (eventError) {
    return { error: "Order dibuat tapi gagal menambah status awal." };
  }

  redirect(`/admin/orders/${shipment.id}`);
}
